[user]
access_key = "xxxxxxx"
cookies = "sid=xxxxx;DedeUserID=xxxxx; DedeUserID__ckMd5=xxxx; SESSDATA=xxx; bili_jct=xxxx"

[comic]
comicId = "xxxx"
ep_str = "1-10"

[setting]
max_threads = 10
epName_rule = "[@ord] @short_title @title"
epName_filter = "False"
